### ISSUE TITLE
Produce stack traces for any errors during Storyscript execution

### ISSUE THREAD

**Issue by judepereira** [storyscript/platform-engine#238]
When an error occurs, there's no way to know in which story, or at which line it happened.

For example:
```coffee
http server as s
    when si listen path:'/fullcontact1' as req
        req write content:(fullcontact person email:req.query_params['email'])
```

The story about produces the following error:
```
Mar 04 17:04:16  ERROR The service "si:latest" was not found in the Asyncy Hub. Hint: 1. Check with the Asyncy team if this service has been made public; 2. Service names are case sensitive
```

A better message would be:
```
RuntimeException: The service "si:latest" was not found in the Asyncy Hub. Hint: 1. Check with the Asyncy team if this service has been made public; 2. Service names are case sensitive
        in hello.story:2
        in hello.story:1
```

The structure for this already exists - AsyncyError is thrown when there's a user related error. It also contains the `story` object, and the `line` object. Prettifying it can be done somewhere in here: 
https://github.com/asyncy/platform-engine/blob/master/asyncy/Logger.py#L24

**Comment by nik72619c** [comment]
Would like to work on this one....could you assign me this task please?

**Comment by judepereira** [comment]
@nik72619c - @bokan is on this issue.

**Comment by nik72619c** [comment]
okay np
