### ISSUE TITLE
Gracefully handle "ImagePull" errors when starting a container

### ISSUE THREAD

**Issue by judepereira** [storyscript/platform-engine#286]
Right now, the engine just freezes indefinitely (as it waits forever for k8s to start the container). However, the k8s error api should also be consumed, to know if the container is unschedule-able.

**Comment by judepereira** [comment]
Rashmi is on this.

**Comment by rashmi43** [comment]
We can use this to retrieve the message why it failed AND then use it to terminate platform-engine gracefully:
 kubectl get pod sample-pod -o go-template="{{range .status.containerStatuses}}{{.state.waiting.message}}{{end}}"
Back-off pulling image "debian-blah"

**Comment by rashmi43** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#containerstate-v1-core

We can query the container state,let me share a sample for the same.
