### ISSUE TITLE
Use GraphQL Subscriptions instead of Postgres Listen

### ISSUE THREAD

**Issue by chrisstpierre** [storyscript/platform-engine#310]
Right now we are using Postgres' built-in for listening.
IE:
```
        glogger.info('Listening for new releases...')
        conn = cls.new_pg_conn(config)
        conn.set_isolation_level(
            psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)

        curs = conn.cursor()
        curs.execute('listen release;')
```

But since we have Graphile on our database we can use graphql [subscribe](https://www.graphile.org/postgraphile/subscriptions/#subscriptions) instead.  I would recommend using this. Also possibly even removing database from anything but the graphql server. Would need to add another issue to storyscript/platform-graphql. Also a migration system on platform-graphql. Thoughts?

**Comment by judepereira** [comment]
We can do this, but this is of no pressing issue right now. Closing for now, will reopen in the future.
