### ISSUE TITLE
No float mutations

### ISSUE THREAD

**Issue by wilzbach** [storyscript/platform-engine#338]
The engine should support mutations on floats

See also: 
- https://github.com/storyscript/platform-engine/blob/ef77bd81cdc7dbaad9e45c58392924d739de29d0/asyncy/processing/Mutations.py
- https://github.com/storyscript/storyscript/blob/master/storyscript/compiler/semantics/functions/HubMutations.py

**Comment by anukul** [comment]
Fixed by https://github.com/storyscript/platform-engine/pull/375
