### ISSUE TITLE
Investigate switching to asyncpg (async Postgres driver)

### ISSUE THREAD

**Issue by wilzbach** [storyscript/platform-engine#347]
https://github.com/MagicStack/asyncpg - a true async Postgres driver.

This could improve the Postgres performance of the engine.

**Comment by wilzbach** [comment]
BTW looking at all the manual Postgres code that has been written here, using a ORM like [SQLalchemy](https://www.sqlalchemy.org/) or [PonyORM](https://ponyorm.org/) might be the better way to go.

**Comment by judepereira** [comment]
Already switched.
