### ISSUE TITLE
Any error in the runtime causes an app to go into the release state FAILED

### ISSUE THREAD

**Issue by judepereira** [storyscript/platform-engine#386]
Only AsyncyExceptions must throw an app into the FAILED state. All other exceptions, must not.
Why?
1. On a deployment of some feature, something fails (because of a programming error), and all apps are then thrown into the FAILED state
2. Instead, only user errors on deployment (marked by the exceptions being subclassed from AsyncyException) must result in the FAILED state.

**Comment by judepereira** [comment]
@anukul also see if it's worth having a new state, since the CLI will spin forever if the app state is not changed.

**Comment by anukul** [comment]
Yeah, I guess `FAILED` is a problem because of the following:
```
Cowardly refusing to deploy app as it's last state is FAILED
```
So, how about a new state called `INTERNAL_ERROR` or something similar?
I'll also modify the CLI to print an appropriate message on that state.

**Comment by judepereira** [comment]
Yea, that sounds good. So the engine will automatically re-deploy apps with INTERNAL_ERROR on a cold start?

Maybe rename it to `TEMP_DEPLOYMENT_FAILURE`?

**Comment by anukul** [comment]
Fixed in https://github.com/storyscript/platform-engine/pull/388
